# Swagger generated server

## Overview
This server was generated by the [swagger-codegen](https://github.com/wordnik/swagger-codegen) project.  By using the 
[swagger-spec](https://github.com/wordnik/swagger-core/wiki) from a remote server, you can easily generate a server stub.  This
is an example of building a swagger-enabled dropwizard server.

This example uses the [dropwizard](http://dropwizard.io/) framework.  To see how to make this your own, look here:

[README](https://github.com/wordnik/swagger-codegen/tree/master/samples/server-generator/scalatra)